language: python

python:
- '3.6'
- '3.5'
- '3.4'

matrix:
  include:
    - python: '3.6'
      env:
      - TOXENV=style EXTRA_PKGS="ShellCheck which"

sudo: required
dist: trusty

services:
  - docker

install:
  - >
    docker build --build-arg PYTHON=python${TRAVIS_PYTHON_VERSION}
    --build-arg EXTRA_PKGS="$EXTRA_PKGS" -t rpmlb .

before_script:
  - sudo chown -R 1000 .

script:
  - >
    docker run -v $(pwd):$(pwd) -w $(pwd) -i
    -e TOXENV=${TOXENV:=py${TRAVIS_PYTHON_VERSION/./}} -t rpmlb
